### ISSUE TITLE
Support for functions autocomplete in PowerShell

### ISSUE THREAD

**Issue by konopkap** [carapace-sh/carapace#1122]
### Request

By design Powershell aliases (created with `Set-Alias` does not support commands with arguments (e.g. `git switch`). It is required to create a function for that:

```pwsh
function gsw { 
    git switch $args
}
```

However with such a definition carapace autocompletion does not work for _alias_ `gsw` - it will only work for full name of `git switch`.

### Proposed solution

Support for functions autocompletion would make carapace more useful with use of _powershell aliases_. Or maybe there's some configuration to already do it - but I missed to find it.

## Polar

<a href="https://polar.sh/carapace-sh/carapace/issues/1122">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/carapace-sh/carapace/issues/1122/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/carapace-sh/carapace/issues/1122/pledge.svg">
</picture>
</a>

**Comment by rsteube** [comment]
You can use a [spec](https://pixi.carapace.sh/spectacularCitizen.html):
```yaml
# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: gsw
parsing: disabled
completion:
  positionalany: ["$carapace.bridge.CarapaceBin([git, switch])"]
```

or alias it with [run](https://pixi.carapace.sh/runningMan.html)
```yaml
# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: gsw
run: "[git, switch]"
```

Save it as `gsw.yaml` in the folder shown in `carapace --help`:
> _Specs are loaded from ..._
